version: "3"

services:
  postgres:
    restart: always
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
  app:
    restart: always
    build: .
    ports:
      - "5000:5000"
    command: >
      sh -c "python app.py"
    volumes:
      - .:/app
